import { CommentType } from '@/types/comments';
import { users } from './users';

export const comments: CommentType[] = [
  {
    owner: users[0],
    id: 1,
    postId: 1,
    description: 'This bakery is close to home! Maybe Ill stop by there... 👀',
  },
  {
    owner: users[1],
    id: 2,
    postId: 1,
    description: 'Really awesome!',
  },
  {
    owner: users[0],
    id: 3,
    postId: 2,
    description: 'I really like this bakery 🥰',
  },
  {
    owner: users[3],
    id: 4,
    postId: 3,
    description: 'Love the creativity in these artworks!',
  },
  {
    owner: users[4],
    id: 5,
    postId: 3,
    description: 'Healthy lunch goals! 🥗',
  },
  {
    owner: users[5],
    id: 6,
    postId: 4,
    description: "What's on the menu? Looks delicious!",
  },
  {
    owner: users[6],
    id: 7,
    postId: 5,
    description: 'City lights are so mesmerizing at night!',
  },
  {
    owner: users[7],
    id: 8,
    postId: 6,
    description: 'Where is this rooftop bar located? I want to visit!',
  },
  {
    owner: users[8],
    id: 9,
    postId: 7,
    description: 'Wow! I wish I could wake up to such a view every day.',
  },
  {
    owner: users[9],
    id: 10,
    postId: 9,
    description: "Nature's masterpiece. Incredible!",
  },
  {
    owner: users[0],
    id: 11,
    postId: 8,
    description: 'Street artists are true visionaries. Love their work!',
  },
  {
    owner: users[1],
    id: 12,
    postId: 9,
    description: 'The colors and details are absolutely stunning.',
  },
  {
    owner: users[2],
    id: 13,
    postId: 5,
    description: 'That salad looks delicious and nutritious!',
  },
  {
    owner: users[3],
    id: 14,
    postId: 3,
    description: "I'm definitely trying this recipe at home!",
  },
  {
    owner: users[4],
    id: 15,
    postId: 2,
    description: 'Cityscapes at night are magical. Where was this taken?',
  },
  {
    owner: users[5],
    id: 16,
    postId: 3,
    description: 'The ambiance in rooftop bars is always so special!',
  },
  {
    owner: users[6],
    id: 17,
    postId: 5,
    description: "What a lovely sunset! Nature's painting.",
  },
  {
    owner: users[7],
    id: 18,
    postId: 1,
    description: 'Sunsets have a calming effect on the soul.',
  },
  {
    owner: users[0],
    id: 19,
    postId: 0,
    description: "This bakery is close to home! Maybe I'll stop by there... 👀",
  },
  {
    owner: users[1],
    id: 20,
    postId: 0,
    description: 'Really awesome!',
  },
  {
    owner: users[2],
    id: 21,
    postId: 1,
    description: 'I really like this bakery 🥰',
  },
  {
    owner: users[3],
    id: 22,
    postId: 1,
    description: 'The pastries are heavenly!',
  },
  {
    owner: users[4],
    id: 23,
    postId: 2,
    description: 'Great atmosphere and delicious treats!',
  },
  {
    owner: users[5],
    id: 24,
    postId: 2,
    description: 'I visit this place every weekend. Can never get enough!',
  },
  {
    owner: users[6],
    id: 25,
    postId: 3,
    description: 'Excellent service and a wide range of products.',
  },
  {
    owner: users[7],
    id: 26,
    postId: 3,
    description: 'The staff is always friendly and helpful.',
  },
  {
    owner: users[8],
    id: 27,
    postId: 4,
    description: 'The pharmacy has all the medicines I need.',
  },
  {
    owner: users[9],
    id: 28,
    postId: 4,
    description: 'Convenient location and reliable service.',
  },
];
